#
#   gitlab-ci.yml -- GitLab CI/CD build instructions
#

image: runner:current

variables:
    PROFILE: "release"
    SECRET_STORE: "embedthis.config/embedthis"

include: "paks/assist/gitlab-makeme.yml"

stages:
    - build
    - publish
