image: runner:current

variables:
    PROFILE: "release"
    SECRET_STORE: "embedthis.config/embedthis"

stages:
    - build
    - publish

build:
    stage: build
    script:
        - ./configure --profile ${PROFILE}
        - me build test package
    artifacts:
        expire_in: 1 hour
        paths:
            - build/*/img/*-*-*.tgz

publish:
    stage: publish
    dependencies:
        - build
    script:
        - $(secrets --env '' --profile ${PROFILE} --store ${SECRET_STORE} get)
        - me configure --profile ${PROFILE}
        - me publish
    only: [ 'tags', 'triggers', 'schedules', 'web', 'api' ]
    tags:
        - embedthis
    environment:
        name: ${PROFILE}
        url: https://www.embedthis.com/pak/download.html
