#
#   gitlab-ci.yml -- GitLab CI/CD build instructions
#

image: alpine-runner:current

variables:
    AWS_ACCOUNT: "embedthis"
    PROFILE: "release"

include: "paks/assist/gitlab-makeme.yml"

stages:
    - build
    - publish
