#
#   gulp-cicd.yml - Template CI/CD for gulp 
#
#   Inputs:
#       PROFILE         dev, release, prod, ...
#       SECRET_STORE    emobrien.config/emobrien
#   Outputs
#       build/web/      rendered pages
#

stages:
    - build
    - publish

build:
    stage: build
    script:
        - cd web ; ./configure --profile ${PROFILE}
        - cd web ; gulp --series build package --profile ${PROFILE}
    artifacts:
        expire_in: 1 hour
        name: "rendered"
        paths:
            - build/

publish:
    stage: publish
    script:
        - $(secrets --env '' --profile ${PROFILE} --store ${SECRET_STORE} get)
        - gulp publish --profile ${PROFILE}
    only: [ 'tags', 'triggers', 'schedules', 'web', 'api' ]
