#
#   gitlab-website.yml - Template CI/CD for gulp
#
#   Inputs:
#       AWS_ACCOUNT     mobsense
#       PARTS           app, src
#       PROFILE         dev, release, prod, ...
#       DIR             "web"
#   Outputs
#       build/web/      rendered pages
#

stages:
    - build
    - publish

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - ${DIR}/node_modules/

build-website:
    stage: build
    script:
        - ./configure --profile ${PROFILE}
        - PARTS=${PARTS} ./paks/assist/build-parts --profile "${PROFILE}"
    artifacts:
        expire_in: 1 hour
        name: "rendered"
        paths:
            - ${DIR}/build/
    tags: ['macosx']

publish-website:
    stage: publish
    script:
        - $(secrets --env '' --profile "${PROFILE}" --aws-profile "${AWS_ACCOUNT}" get)
        - ./configure --profile ${PROFILE}
        - npm link gulp
        - PARTS=${PARTS} ./paks/assist/publish-parts --profile "${PROFILE}"
    only: [ 'tags', 'triggers', 'schedules', 'web', 'api' ]
    tags: ['macosx']
